### ISSUE TITLE
Fablib uses the same key for all slices.

### ISSUE THREAD

**Issue by 842Mono** [fabric-testbed/fabrictestbed-extensions#10]
Users may use different keys for different slices. But currently, fablib assumes that all slices are created with the same key.

We need to somehow store the different keys that are used to access the different slices. Or maybe, we don't have to go over all slices when we are working with one slice.

**Comment by paul-ruth** [comment]
This one probably needs us to wait until proper key management is implemented in FABRIC/portal.  Then we can implement a solution that works with the long-term key management system.
