### ISSUE TITLE
Connections left over at Bastion hosts when using fablib

### ISSUE THREAD

**Issue by paul-ruth** [fabric-testbed/fabrictestbed-extensions#110]
https://fabric-testbed.atlassian.net/browse/FIP-300

Description

As per suggestion from you and Ilya, i ran the “Hello World” jupyter hub notebook and tracked the ssh connections on the bastion host. Usually for jump ssh connections, the bastions should see two sshd connection processes for each session. These are

user host/jupyter to bastion

bastion to end host(user VM)

Upon completion of the task from jupyter, both the above connections should close. But upon observation, i found that (2) is closed , but (1) remains.  Upon subsequent operations similar to these the bastions end up accumulating lots of these leftover connections for each user using fablib. The connections dont go away until a timeout or when jupyter hub session is terminated. So when FABRIC is busy with many users there comes a time when new connections to bastions are denied since the MAXStartup connection limit for SSH is reached. 

Root cause

bastion.close() calls missing in the fablib code. One such example is https://github.com/fabric-testbed/fabrictestbed-extensions/blob/dfecd98cfd02d1b789a3129367f7fc61fa47009d/fabrictestbed_extensions/fablib/node.py#L1348 . Closing the bastion Channel does not automatically close the ssh connections. An explicit bastion.close() is required.

**Comment by sajith** [comment]
Some notes to myself. Did some quick local testing, with:

```python
client = SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect("localhost")
```

It seems that paramiko connections stay around (noticeable with `netstat) until `client.close()` is called.

Upon grepping for `paramiko.SSHClient`, there are three methods that open connections to bastion:

- `fablib.node.execute()`
- `fablib.node.upload_file()`
- `fablib.node.download_file()`

For a simple fix, I suppose we could call `close()` on each of those above `SSHClient`  instances.  A better solution might be doing cleanup in a `finally` block, or maybe using a context manager.
