### ISSUE TITLE
Duplicated methods in Resources class

### ISSUE THREAD

**Issue by sajith** [fabric-testbed/fabrictestbed-extensions#250]
`Resources.get_site_names()` and `Resources.get_site_list()` are doing the same thing:

https://github.com/fabric-testbed/fabrictestbed-extensions/blob/e716c26b0aa8d04a8103922bb892500329f22c2d/fabrictestbed_extensions/fablib/resources.py#L197-L208

https://github.com/fabric-testbed/fabrictestbed-extensions/blob/e716c26b0aa8d04a8103922bb892500329f22c2d/fabrictestbed_extensions/fablib/resources.py#L639-L655

**Comment by kthare10** [comment]
This is no longer the case after the Resource class was refactored in #332
