### ISSUE TITLE
Bastion private address getters 

### ISSUE THREAD

**Issue by sajith** [fabric-testbed/fabrictestbed-extensions#257]
`FablibManager.get_bastion_private_ipv4_addr()` and `FablibManager.get_bastion_private_ipv6_addr()` do not seem to return addresses that are meaningful.

```python
>>> from fabrictestbed_extensions.fablib.fablib import FablibManager
>>> fablib = FablibManager(offline=True)
>>> fablib.get_bastion_private_ipv4_addr()
'0.0.0.0'
>>> fablib.get_bastion_private_ipv6_addr()
'0:0:0:0:0:0'
```

Why would be these addresses useful? Could we perhaps remove these methods?

**Comment by nbastin** [comment]
This is probably pointless at this juncture, but these methods used to return good values when you were in a real scenario - the fact that they returned 0.0.0.0 in offline mode is not surprising.  Losing this is kinda terrible for real use cases where the bastions had complex routing.

**Comment by sajith** [comment]
@nbastin Thanks! I'm not familiar with those good old values, so I was hoping that someone would chime in. What were those private addresses, and how were they useful?  

In my reading of the code at the time, the addresses I'm talking above were hard-coded (see PR #259), and not peculiar to offline mode. That code seems to have gone away now. I haven't done the archeology yet, so I'm not sure when and why that happened.

As far as I know, these days `bastion.fabric-testbed.net` is a couple of jump hosts load-balanced by DNS, and in general people are not supposed to care about their actual addresses.  I also do not know what the "private" part here meant.  I wouldn't be opposed to adding an equivalent API back, if there's a reasonable use for them.

**Comment by nbastin** [comment]
Yeah, I wasn't super clear in my comment...these values could be set by the testbed environment (or the user) if you were running fablib on the _inside_ of the environment (or a test environment, more likely, since I'm not sure how well this ever worked in the actual FABRIC testbed), giving you a sideband to access all the other nodes in your topology for command and control even if your dataplane routing wouldn't otherwise allow an in-slice CNC node to reach everyone.

**Comment by nbastin** [comment]
Just to be clear - I have no idea if this was how they were supposed to be used, it's just how we _did_ use them.. :-)

**Comment by sajith** [comment]
That is an interesting use case!  

In my mind this is a client library meant to be used by Jupyter notebooks or Python apps that run _outside_ of the testbed. This is the first time I'm hearing about usage of this library inside of the testbed. (I must not have been looking very hard...) I don't even know which assumptions we made will not hold when this library is used inside of the testbed. :-)

Looks like the code we're talking about here went away in PR #271 (commit f0c0c83), so this issue is no longer valid. Those methods weren't returning any meaningful values anyway.  

I will close this issue (and PR #259) for now.  Let us revisit this topic if the need for this functionality arises again.
