### ISSUE TITLE
`FablibManager.show_table()` and `FablibManager.list_table()` are quite similar

### ISSUE THREAD

**Issue by sajith** [fabric-testbed/fabrictestbed-extensions#370]
While working on #369, it appeared to me that [`FablibManager.list_table()`](https://github.com/fabric-testbed/fabrictestbed-extensions/blob/7a54c65f2580bfd3e6d7bdc02ce9668f8888172b/fabrictestbed_extensions/fablib/fablib.py#L2393) and [`FablibManager.show_table()`](https://github.com/fabric-testbed/fabrictestbed-extensions/blob/7a54c65f2580bfd3e6d7bdc02ce9668f8888172b/fabrictestbed_extensions/fablib/fablib.py#L2248) are very similar.

Each of them have their "helper" methods also (such as `show_table_text()` and `list_table_text()`, `show_table_jupyter()` and `list_table_jupyter()`, so on), which are also very similar.  

@paul-ruth @kthare10 Is there a reason to keep both `list_table()` and `show_table()`? Does it makes sense to remove the duplicates?

**Comment by kthare10** [comment]
@sajith - show_table is for a single entity like a slice object and works on data i.e. dict object
list_table is for list of objects like when you list slivers in a slice or sites, data being passed is a list instead of dict.
Filtering works accordingly, both look pretty similar but intended to serve different purposes.

**Comment by sajith** [comment]
@kthare10 Aha. Thank you, that makes sense. That will help me document these better.

It would be nice to refactor the code that is common to both methods, but I don't know if it is worth the effort at this point. Perhaps we can keep this issue open so that we can maybe revisit this when it makes sense?

**Comment by kthare10** [comment]
Refactoring would involve lot of testing, I would leave this as is. For now, Please consider marking this as NoFix, we can re-open it, if we plan to fix this later.

**Comment by sajith** [comment]
Sure. Perhaps we can have a `format_table()` and a `display_table()` that can seamlessly work with either types of data, and eventually deprecate the other two. That should make things a little easier to use and easier to test. And it would be nice to have more tests so that we can bravely refactor things like this. :-)

**Comment by sajith** [comment]
I am leaving some notes here, because otherwise I would have forgotten what I was thinking when revisiting this in the future.

My reading is that `list_table()` expects `data` parameter of `List[Dict[str,str]]` type, because we take `data` and do this:

https://github.com/fabric-testbed/fabrictestbed-extensions/blob/7a54c65f2580bfd3e6d7bdc02ce9668f8888172b/fabrictestbed_extensions/fablib/fablib.py#L2412-L2413

Also, `show_table()` appears to expect `data` parameter as a `Dict[str, str]`, because we do this in `create_show_table()`:

https://github.com/fabric-testbed/fabrictestbed-extensions/blob/7a54c65f2580bfd3e6d7bdc02ce9668f8888172b/fabrictestbed_extensions/fablib/fablib.py#L2462-L2476

It is not super clear to me if the aforementioned types could be `List[Dict[Hashable,Any]]` (or `Iterable[Dict[Hashable, Any]]`) and `Dict[Hashable, Any]` respectively.

Another thing is that both `list_table_jupyter()` and `show_table_jupyter()` form a Pandas `DataFrame`, whose `data` argument can be "ndarray (structured or homogeneous), Iterable, dict, or DataFrame"

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame

It also seems that the methods that format/display tables do not have to be in `FablibManager`.  They can be free-standing, and thus made a little easier to test independently. 

Anyway, it would be good to have some tests.
