### ISSUE TITLE
slice.renew() should pass **kwargs through to slice.submit()

### ISSUE THREAD

**Issue by nbastin** [fabric-testbed/fabrictestbed-extensions#374]
`slice.renew()` calls through to `slice.submit()` after validating the input arguments, but forces the caller to be stuck with the default behaviour of `slice.submit()`, which may be very undesirable.

**Comment by nbastin** [comment]
I don't think 376 fixes this, but it addresses primary issues.

**Comment by kthare10** [comment]
Updated the code to apply kwargs.
