### ISSUE TITLE
Execute commands using different user

### ISSUE THREAD

**Issue by TristanJordan99** [fabric-testbed/fabrictestbed-extensions#47]
A way to login with another user and execute commands could be useful. I was trying to use a user that I created (outside of the default ubuntu) and didn't see an in library way of doing so. A different user would contain a different name and key file (created by the user).

**Comment by paul-ruth** [comment]
Thats a good idea. I think I will add a couple extra optional parameters to execute/upload/download that allow you to override the standard username and private key file. 

It will look something like:

def execute(self, command, retry=3, retry_interval=10), username=None, private_user_key_file=None)

If the the username and/or private_user_key_file and not passed in, the behavior will be the same as it is now.

**Comment by kthare10** [comment]
This has been implemented and supported via https://github.com/fabric-testbed/fabrictestbed-extensions/blob/main/fabrictestbed_extensions/fablib/node.py#L1295

Closing the issue.
